#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (division, print_function, absolute_import,
                        unicode_literals)

__all__ = []

import fileinput

for line in fileinput.input():
    args = line.split()
    print(args)
